### ISSUE TITLE
How to get the inference result of apple52 blendshapes from single video file?

### ISSUE THREAD

**Issue by jinfagang** [LizhenWangT/FaceVerse#9]
Hi, how to get the inference result of apple52 blendshapes? I saw the code only have a optimization based function, this could be every time-consuming.
I though it could a be single model outputs all blendshapes and rotation in a single forward.

**Comment by LizhenWangT** [comment]
The exp_tensor in model/FaceVerse.py is the 52 expression-related parameters (blendshapes) with the corresponding name in model_dict['exp_name_list']. I think it's quite difficult to get stable results of pose and expression parameters in a single forward. We have demonstrate the optimization can be accelerated to real-time using CUDA-based point rendering, as shown in [Fig.4](https://github.com/LizhenWangT/FaceVerse/blob/main/docs/tracking_v2_2.gif). But I'm so sorry, we are not going to release this version for the time being.

**Comment by jinfagang** [comment]
@LizhenWangT  How does optimize based method able to realtime? How many iteration it need? Did u test the time of optimization? the rendering part is OK, that part time isn't the biggest one I think.

**Comment by LizhenWangT** [comment]
Actually, the biggest time-consuming process is surface-based differentiable rendering in this version. Because we need to render an image in each "fitting with differentiable rendering" step and the backward propagation is also quite time-consuming. We need to render more than 10 images for the optimization of each frame. In the accelarated version, we use many multi-process and multi-batch optimzation. We use 15 iterations for "fitting only using landmarks" and 10 iterations for "fitting with differentiable rendering" (which is changed to CUDA-based point rendering rather than pytorch3D-based surface rendering), which results in 0.06s when batchsize=1 and 0.033s in average when batchsize=3. Since the biggest part time is the optimzation, other steps can be handled in other threads. We finnaly get a 0,033s per frame with about a 0.2s delay tracking algorithm.

**Comment by jinfagang** [comment]
I see.... I am searching for a learning based method though. We have a single forward version prediction 52 blendshapses within 0.005s, but I need something better, optimization based is not my direction.

**Comment by enjoybo** [comment]
> I see.... I am searching for a learning based method though. We have a single forward version prediction 52 blendshapses within 0.005s, but I need something better, optimization based is not my direction.

Hello, is your single forward model based on Faceverse basis?

**Comment by MarcoG5** [comment]
> I see.... I am searching for a learning based method though. We have a single forward version prediction 52 blendshapses within 0.005s, but I need something better, optimization based is not my direction.

Hello, is there any learning based method for blendshape prediction that you can share? I am interested in those kind of methods.

**Comment by enjoybo** [comment]
这是来自QQ邮箱的自动回复邮件。邮件已收到，谢谢!
